/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.formularios;

import com.formdev.flatlaf.FlatIntelliJLaf;
import Controlador.CRUDCompra;
import Controlador.CRUDCompraProducto;
import Controlador.CRUDProducto;
import Vista.formularios.GestionCompras;
import Controlador.CRUDProveedor;
import Modelo.POJOCompra;
import Modelo.POJOCompraProducto;
import Modelo.POJOProducto;
import Vista.Menu.Main;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Joy Cruz
 */
public class Compras extends javax.swing.JInternalFrame {

    /**
     * Creates new form Compras
     */
    double totalpagar;
    DefaultTableModel modelo = new DefaultTableModel();
    POJOProducto p = new POJOProducto();
    double total;
    int cant;
    double precio;
     int DatoSeleccionado = -1;
    
    public Compras() {
        initComponents();
        
        FlatIntelliJLaf.setup();
        
        Fecha.setText(fechaActual());
        
        TablaProducto.getTableHeader().setFont(new Font("Seoge UI Emoji", Font.PLAIN, 14));
        TablaProducto.getTableHeader().setOpaque(false);
        TablaProducto.getTableHeader().setBackground(new Color(51,102,255));
        TablaProducto.getTableHeader().setForeground(new Color(255,255,255));
        TablaProducto.setRowHeight(25);
    }

    public static String fechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY-MM-dd");
        return formatofecha.format(fecha);
    }
    
    public void mostrar() {
        try {
            DefaultTableModel modelo;
            CRUDCompra com = new CRUDCompra();
            modelo = com.mostrarDatos();
            GestionCompras.TablaCompras.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
        
        public void limpiar() {
            CedProveedor.setText("");
            NombreProveedor.setText("");
            Fecha.setText("");
            CodProducto.setText("");
            NombreProducto.setText("");
            Precio.setText("");
            Stock.setText("");
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator9 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BuscarProveedor = new Vista.Menu.BorderPanel();
        jLabel3 = new javax.swing.JLabel();
        CedProveedor = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        NombreProveedor = new javax.swing.JTextField();
        Proveedor2 = new javax.swing.JLabel();
        Proveedor1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        Proveedor = new javax.swing.JLabel();
        CodProducto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        BuscarProducto = new Vista.Menu.BorderPanel();
        jLabel4 = new javax.swing.JLabel();
        Proveedor3 = new javax.swing.JLabel();
        NombreProducto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Proveedor4 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JSpinner();
        jSeparator6 = new javax.swing.JSeparator();
        Proveedor5 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Proveedor6 = new javax.swing.JLabel();
        Stock = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        AgregarProducto = new Vista.Menu.BorderPanel();
        jLabel5 = new javax.swing.JLabel();
        Borrar = new Vista.Menu.BorderPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        Proveedor8 = new javax.swing.JLabel();
        prese = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Proveedor9 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        Proveedor7 = new javax.swing.JLabel();
        totalPagar = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        Guardar = new Vista.Menu.BorderPanel();
        jLabel7 = new javax.swing.JLabel();
        Cancelar = new Vista.Menu.BorderPanel();
        jLabel9 = new javax.swing.JLabel();
        Fecha = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Compras");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)), "Datos de Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 0, 18), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Proveedor");

        BuscarProveedor.setBackground(new java.awt.Color(51, 102, 255));
        BuscarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarProveedorMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar");

        javax.swing.GroupLayout BuscarProveedorLayout = new javax.swing.GroupLayout(BuscarProveedor);
        BuscarProveedor.setLayout(BuscarProveedorLayout);
        BuscarProveedorLayout.setHorizontalGroup(
            BuscarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarProveedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        BuscarProveedorLayout.setVerticalGroup(
            BuscarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        CedProveedor.setBackground(new java.awt.Color(255, 255, 255));
        CedProveedor.setBorder(null);
        CedProveedor.setForeground(new java.awt.Color(51, 51, 51));
        try {
            CedProveedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CedProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));

        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));

        NombreProveedor.setBackground(new java.awt.Color(255, 255, 255));
        NombreProveedor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        NombreProveedor.setForeground(new java.awt.Color(51, 51, 51));
        NombreProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreProveedor.setBorder(null);
        NombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreProveedorKeyTyped(evt);
            }
        });

        Proveedor2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor2.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor2.setText("CED: Proveedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CedProveedor)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jSeparator1)
                                .addComponent(NombreProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(Proveedor2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Proveedor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CedProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        Proveedor1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor1.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor1.setText("Fecha");

        jSeparator3.setForeground(new java.awt.Color(51, 102, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)), "Datos de Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 0, 18), new java.awt.Color(51, 102, 255))); // NOI18N

        Proveedor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor.setText("COD: Producto");

        CodProducto.setBackground(new java.awt.Color(255, 255, 255));
        CodProducto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        CodProducto.setForeground(new java.awt.Color(51, 51, 51));
        CodProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CodProducto.setBorder(null);

        jSeparator4.setForeground(new java.awt.Color(51, 102, 255));

        BuscarProducto.setBackground(new java.awt.Color(51, 102, 255));
        BuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarProductoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");

        javax.swing.GroupLayout BuscarProductoLayout = new javax.swing.GroupLayout(BuscarProducto);
        BuscarProducto.setLayout(BuscarProductoLayout);
        BuscarProductoLayout.setHorizontalGroup(
            BuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarProductoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        BuscarProductoLayout.setVerticalGroup(
            BuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        Proveedor3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor3.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor3.setText("Cantidad");

        NombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        NombreProducto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        NombreProducto.setForeground(new java.awt.Color(51, 51, 51));
        NombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreProducto.setBorder(null);
        NombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreProductoKeyTyped(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(51, 102, 255));

        Proveedor4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor4.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor4.setText(" Producto");

        Cantidad.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Cantidad.setBorder(null);

        jSeparator6.setForeground(new java.awt.Color(0, 102, 255));

        Proveedor5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor5.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor5.setText("Precio de Compra");

        Precio.setBackground(new java.awt.Color(255, 255, 255));
        Precio.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Precio.setForeground(new java.awt.Color(51, 51, 51));
        Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Precio.setBorder(null);

        jSeparator7.setForeground(new java.awt.Color(51, 102, 255));

        Proveedor6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor6.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor6.setText("Stock");

        Stock.setBackground(new java.awt.Color(255, 255, 255));
        Stock.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Stock.setForeground(new java.awt.Color(51, 51, 51));
        Stock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Stock.setBorder(null);

        jSeparator10.setForeground(new java.awt.Color(51, 102, 255));

        TablaProducto.setBackground(new java.awt.Color(255, 255, 255));
        TablaProducto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        TablaProducto.setForeground(new java.awt.Color(51, 51, 51));
        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Producto", "Nombre", "Cantidad", "Precio", "Total"
            }
        ));
        TablaProducto.setGridColor(new java.awt.Color(255, 255, 255));
        TablaProducto.setRowHeight(25);
        TablaProducto.setSelectionBackground(new java.awt.Color(102, 153, 255));
        TablaProducto.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaProducto.getTableHeader().setReorderingAllowed(false);
        TablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProducto);

        AgregarProducto.setBackground(new java.awt.Color(51, 102, 255));
        AgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarProductoMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Agregar");

        javax.swing.GroupLayout AgregarProductoLayout = new javax.swing.GroupLayout(AgregarProducto);
        AgregarProducto.setLayout(AgregarProductoLayout);
        AgregarProductoLayout.setHorizontalGroup(
            AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18))
        );
        AgregarProductoLayout.setVerticalGroup(
            AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        Borrar.setBackground(new java.awt.Color(51, 102, 255));
        Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Borrar");

        javax.swing.GroupLayout BorrarLayout = new javax.swing.GroupLayout(Borrar);
        Borrar.setLayout(BorrarLayout);
        BorrarLayout.setHorizontalGroup(
            BorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        BorrarLayout.setVerticalGroup(
            BorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jSeparator13.setForeground(new java.awt.Color(51, 102, 255));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Proveedor8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor8.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor8.setText("Presentación");

        prese.setBackground(new java.awt.Color(255, 255, 255));
        prese.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        prese.setForeground(new java.awt.Color(51, 51, 51));
        prese.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prese.setBorder(null);

        jSeparator12.setForeground(new java.awt.Color(51, 102, 255));

        Proveedor9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor9.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor9.setText("Marca");

        marca.setBackground(new java.awt.Color(255, 255, 255));
        marca.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        marca.setForeground(new java.awt.Color(51, 51, 51));
        marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marca.setBorder(null);

        jSeparator15.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Proveedor)
                                .addComponent(Proveedor8)
                                .addComponent(Proveedor4)
                                .addComponent(jSeparator5)
                                .addComponent(prese)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NombreProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CodProducto)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Proveedor3)
                            .addComponent(Proveedor5)
                            .addComponent(jSeparator6)
                            .addComponent(Precio)
                            .addComponent(jSeparator7)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Proveedor6)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Proveedor9)
                                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Proveedor3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Proveedor5)
                        .addGap(3, 3, 3)
                        .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Proveedor6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Proveedor9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marca)
                            .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(Proveedor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Proveedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Proveedor8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(prese, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(AgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jSeparator11.setForeground(new java.awt.Color(51, 102, 255));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Proveedor7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Proveedor7.setForeground(new java.awt.Color(51, 102, 255));
        Proveedor7.setText("Total a pagar");

        totalPagar.setBackground(new java.awt.Color(255, 255, 255));
        totalPagar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        totalPagar.setForeground(new java.awt.Color(51, 51, 51));
        totalPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPagar.setToolTipText("");
        totalPagar.setBorder(null);

        jSeparator19.setForeground(new java.awt.Color(51, 102, 255));

        Guardar.setBackground(new java.awt.Color(51, 102, 255));
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Guardar");

        javax.swing.GroupLayout GuardarLayout = new javax.swing.GroupLayout(Guardar);
        Guardar.setLayout(GuardarLayout);
        GuardarLayout.setHorizontalGroup(
            GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GuardarLayout.setVerticalGroup(
            GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        Cancelar.setBackground(new java.awt.Color(51, 102, 255));
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cancelar");

        javax.swing.GroupLayout CancelarLayout = new javax.swing.GroupLayout(Cancelar);
        Cancelar.setLayout(CancelarLayout);
        CancelarLayout.setHorizontalGroup(
            CancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancelarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(30, 30, 30))
        );
        CancelarLayout.setVerticalGroup(
            CancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Fecha.setBackground(new java.awt.Color(255, 255, 255));
        Fecha.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(51, 51, 51));
        Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fecha.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Proveedor1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalPagar)
                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Proveedor7)
                        .addGap(11, 11, 11)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Proveedor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Proveedor7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProveedorMouseClicked
        CRUDProveedor cc = new CRUDProveedor();
        CedProveedor.setText(cc.buscarDatosProveedor(NombreProveedor.getText()));
    }//GEN-LAST:event_BuscarProveedorMouseClicked

    private void NombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreProveedorKeyTyped
        char car = evt.getKeyChar();
        if ((car< 'a' || car> 'z')&& (car < 'A' || car> 'z')
            && car != 'á'
            && car != 'é'
            && car != 'í'
            && car != 'ó'
            && car != 'ú'
            && car != 'Á'
            && car != 'É'
            && car != 'Í'
            && car != 'Ó'
            && car != 'Ú'
            && car != 'Ü'
            && car != 'ü'
            && car != 'Ñ'
            && car != 'ñ'
            && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreProveedorKeyTyped

    private void BuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProductoMouseClicked
        ProductoCompra pro = new ProductoCompra();
        int x = (Main.desktopPane.getWidth() / 2) - pro.getWidth() / 2;
        int y = ((Main.desktopPane.getHeight() / 2) - pro.getHeight() / 2) - 10;
        pro.setLocation(x, y);
        Main.desktopPane.add(pro);
        pro.toFront();
        pro.setVisible(true);
    }//GEN-LAST:event_BuscarProductoMouseClicked

    private void NombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreProductoKeyTyped
        char car = evt.getKeyChar();
        if ((car< 'a' || car> 'z')&& (car < 'A' || car> 'z')
            && car != 'á'
            && car != 'é'
            && car != 'í'
            && car != 'ó'
            && car != 'ú'
            && car != 'Á'
            && car != 'É'
            && car != 'Í'
            && car != 'Ó'
            && car != 'Ú'
            && car != 'Ü'
            && car != 'ü'
            && car != 'Ñ'
            && car != 'ñ'
            && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreProductoKeyTyped

    private void TablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductoMouseClicked
        DatoSeleccionado = TablaProducto.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaProductoMouseClicked

    private void AgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarProductoMouseClicked
        agregarProducto();
    }//GEN-LAST:event_AgregarProductoMouseClicked

    public void agregarProducto(){
        modelo=(DefaultTableModel)TablaProducto.getModel();
        int id=Integer.parseInt(CodProducto.getText().toString());
        String nom=NombreProducto.getText();
        cant=Integer.parseInt(Cantidad.getValue().toString());
        precio=Double.parseDouble(Precio.getText());
        int stock=Integer.parseInt(Stock.getText());
        total=cant*precio;
        ArrayList lista = new ArrayList();
        if(stock>0){
            lista.add(id);
            lista.add(nom);
            lista.add(cant);
            lista.add(precio);
            lista.add(total);
            Object[]ob=new Object[5];
            ob[0]=lista.get(0);
            ob[1]=lista.get(1);
            ob[2]=lista.get(2);
            ob[3]=lista.get(3);
            ob[4]=lista.get(4);
            modelo.addRow(ob);
            TablaProducto.setModel(modelo);
            calcularTotal();
        }else{
            JOptionPane.showMessageDialog(this, "Stock de producto insuficiente");
        }
    }
    
    public void calcularTotal() {
        totalpagar=0;
        for (int i = 0; i < TablaProducto.getRowCount(); i++) {
            cant=Integer.parseInt(TablaProducto.getValueAt(i, 2).toString());
            precio=Double.parseDouble(TablaProducto.getValueAt(i, 3).toString());
            totalpagar=totalpagar+(cant*precio);
        }
        totalPagar.setText(""+totalpagar);
    }
    
    private void BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarMouseClicked
        if (DatoSeleccionado >= 0) {
            int fila = TablaProducto.getSelectedRow();
            modelo.removeRow(fila);
        } else{
            JOptionPane.showConfirmDialog(null, "Seleccione el dato a eliminar");
        }
    }//GEN-LAST:event_BorrarMouseClicked

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
        try {
            if ((Fecha.getText().equals("    -  -  "))
                || (CedProveedor.getText().equals("   -      -     "))) {
                JOptionPane.showMessageDialog(null,
                    "Tiene datos vacíos");
            } else if(TablaProducto.getRowCount()<0){
                JOptionPane.showMessageDialog(null, "Debe añadir a la tabla al menos un producto");
            }
            else {
                String FechaCompra = (Fecha.getText().toString());
                String CedulaP = (CedProveedor.getText().toString());

                POJOCompra cc = new POJOCompra(FechaCompra, CedulaP);
                CRUDCompra com = new CRUDCompra();
                com.Guardar(cc);

                for (int i = 0; i < modelo.getRowCount(); i++) {
                    int IDProducto = Integer.parseInt(TablaProducto.getValueAt(i, 0).toString());
                    double PrecioCompra = Double.parseDouble(TablaProducto.getValueAt(i, 3).toString());
                    int CantProductosComprados = Integer.parseInt(TablaProducto.getValueAt(i, 2).toString());
                    double total = Double.parseDouble(TablaProducto.getValueAt(i, 4).toString());
                    POJOCompraProducto cg = new POJOCompraProducto(IDProducto, PrecioCompra, CantProductosComprados, total);
                    CRUDCompraProducto ccg = new CRUDCompraProducto();
                    ccg.InsertarCompraProducto(cg);
                    mostrar();
                    limpiar();
                    dispose();
                }
                JOptionPane.showMessageDialog(null, "Datos Guardados correctamente");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error" + e);

        }
    }//GEN-LAST:event_GuardarMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        dispose();
    }//GEN-LAST:event_CancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.Menu.BorderPanel AgregarProducto;
    private Vista.Menu.BorderPanel Borrar;
    private Vista.Menu.BorderPanel BuscarProducto;
    private Vista.Menu.BorderPanel BuscarProveedor;
    private Vista.Menu.BorderPanel Cancelar;
    private javax.swing.JSpinner Cantidad;
    public static javax.swing.JFormattedTextField CedProveedor;
    public static javax.swing.JTextField CodProducto;
    private javax.swing.JTextField Fecha;
    public static Vista.Menu.BorderPanel Guardar;
    public static javax.swing.JTextField NombreProducto;
    public static javax.swing.JTextField NombreProveedor;
    private javax.swing.JTextField Precio;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JLabel Proveedor1;
    private javax.swing.JLabel Proveedor2;
    private javax.swing.JLabel Proveedor3;
    private javax.swing.JLabel Proveedor4;
    private javax.swing.JLabel Proveedor5;
    private javax.swing.JLabel Proveedor6;
    private javax.swing.JLabel Proveedor7;
    private javax.swing.JLabel Proveedor8;
    private javax.swing.JLabel Proveedor9;
    public static javax.swing.JTextField Stock;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    public static javax.swing.JTextField marca;
    public static javax.swing.JTextField prese;
    private javax.swing.JTextField totalPagar;
    // End of variables declaration//GEN-END:variables
}
