/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.formularios;

import Controlador.CRUDCliente;
import java.awt.event.KeyEvent;
import Controlador.CRUDProveedor;
import Modelo.POJOProveedor;
import Vista.Menu.Menu;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joy Cruz
 */
public class VistaProveedor extends javax.swing.JInternalFrame {

    int datoSeleccionado = -1;

    /**
     * Creates new form VistaProveedor
     */
    public VistaProveedor() {
        initComponents();
        mostrar();
        BotonMostrar.setVisible(false);
        InsertarProveedor.setVisible(false);
    }

    public void mostrar() {
        try {
            DefaultTableModel modelo;
            CRUDProveedor pro = new CRUDProveedor();
            modelo = pro.mostrarDatos();
            TablaProveedor.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaProveedor = new javax.swing.JTable();
        EliminarProveedor = new javax.swing.JButton();
        BuscarProveedor = new javax.swing.JTextField();
        EditarProveedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        BotonMostrar = new javax.swing.JButton();
        InsertarProveedor = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión de proveedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36), new java.awt.Color(0, 102, 255))); // NOI18N

        TablaProveedor.setBackground(new java.awt.Color(204, 204, 255));
        TablaProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TablaProveedor.setForeground(new java.awt.Color(51, 51, 51));
        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de proveedor", "Nombres", "Apellidos", "Teléfono", "Dirección"
            }
        ));
        TablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProveedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaProveedor);

        EliminarProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EliminarProveedor.setForeground(new java.awt.Color(0, 102, 255));
        EliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/borrar.png"))); // NOI18N
        EliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProveedorActionPerformed(evt);
            }
        });

        BuscarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        BuscarProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BuscarProveedor.setForeground(new java.awt.Color(51, 51, 51));
        BuscarProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscarProveedorFocusLost(evt);
            }
        });
        BuscarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarProveedorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarProveedorMousePressed(evt);
            }
        });
        BuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarProveedorKeyReleased(evt);
            }
        });

        EditarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/editar.png"))); // NOI18N
        EditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProveedorActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/buscar1.png"))); // NOI18N

        Agregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Agregar.setText("+");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });

        InsertarProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        InsertarProveedor.setForeground(new java.awt.Color(51, 102, 255));
        InsertarProveedor.setText("Insertar");
        InsertarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(Agregar)
                                .addGap(18, 18, 18)
                                .addComponent(EditarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(BotonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(InsertarProveedor)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BotonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EliminarProveedor)
                        .addComponent(EditarProveedor))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Agregar))
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InsertarProveedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProveedorMouseClicked
        datoSeleccionado = TablaProveedor.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaProveedorMouseClicked

    private void EliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProveedorActionPerformed
        if (datoSeleccionado >= 0) {
            String dato = String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 0));
            CRUDProveedor pro = new CRUDProveedor();
            if (JOptionPane.showConfirmDialog(rootPane,
                    "Se eliminará el registro, ¿Desea continuar?",
                    "Eliminar Registro",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                pro.eliminar(dato);
                mostrar();
                JOptionPane.showMessageDialog(null,
                        "Dato eliminado correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar un registro de la tabla");
        }

    }//GEN-LAST:event_EliminarProveedorActionPerformed

    private void EditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProveedorActionPerformed
       Proveedor prove = new Proveedor();
        int x = (Menu.desktopPane.getWidth() / 2) - prove.getWidth() / 2;
        int y = (Menu.desktopPane.getHeight() / 2) - prove.getHeight() / 2;
        prove.setLocation(x, y);
        Menu.desktopPane.add(prove);

        if (datoSeleccionado >= 0) {
            //mandar datos al formulario
            Proveedor.Ced.setText(String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 0)));
            Proveedor.NombresP.setText(String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 1)));
            Proveedor.ApellidosP.setText(String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 2)));
            Proveedor.DirecP.setText(String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 3)));
            Proveedor.TelProveedor.setText(String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 4)));
            Proveedor.Correo.setText(String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 5)));
            Proveedor.Ced.enable(false);
            //hacer al frente y visible
            prove.toFront();
            Proveedor.GuardarProveedor.setVisible(false);
            Proveedor.ActualizarProveedor.setVisible(true);
            Proveedor.Cancelar.setVisible(true);
            prove.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro a actualizar");
        }
    }//GEN-LAST:event_EditarProveedorActionPerformed

    private void BuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarProveedorKeyReleased
        try {

            DefaultTableModel modelo;
            CRUDProveedor pro = new CRUDProveedor();
            modelo = pro.buscarDatos(BuscarProveedor.getText());
            TablaProveedor.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BuscarProveedorKeyReleased

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
          Proveedor pro = new Proveedor();
        int x = (Menu.desktopPane.getWidth() / 2) - pro.getWidth() / 2;
        int y = (Menu.desktopPane.getHeight() / 2) - pro.getHeight() / 2;
        pro.setLocation(x, y);
        Menu.desktopPane.add(pro);
        pro.toFront();
        pro.setVisible(true);
    }//GEN-LAST:event_AgregarActionPerformed

    private void BuscarProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarProveedorFocusLost
       BuscarProveedor.setText("Buscar por cédula, nombres o apellidos");
       BuscarProveedor.setForeground(Color.gray);
    }//GEN-LAST:event_BuscarProveedorFocusLost

    private void BuscarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProveedorMouseClicked
       BuscarProveedor.setText("");
    }//GEN-LAST:event_BuscarProveedorMouseClicked

    private void BuscarProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProveedorMousePressed
         BuscarProveedor.setText("");
        BuscarProveedor.setForeground(Color.black);
    }//GEN-LAST:event_BuscarProveedorMousePressed

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_BotonMostrarActionPerformed

    private void InsertarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarProveedorActionPerformed
      if (datoSeleccionado >=0){
          VistaCompra.CodProveedor.setText(String.valueOf(TablaProveedor.getValueAt(datoSeleccionado, 0)));
          dispose(); 
          JOptionPane.showMessageDialog(null, "Dato agregado correctamente");
      }else{
         JOptionPane.showMessageDialog(null, "Debe seleccionar un registro"); 
      }
    }//GEN-LAST:event_InsertarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JTextField BuscarProveedor;
    public static javax.swing.JButton EditarProveedor;
    public static javax.swing.JButton EliminarProveedor;
    public static javax.swing.JButton InsertarProveedor;
    public static javax.swing.JTable TablaProveedor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
