/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.formularios;
import java.awt.event.KeyEvent;
import Controlador.CRUDEmpleado;
import Modelo.POJOEmpleado;
import Vista.Menu.Menu;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Joy Cruz
 */
public class VistaEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaEmpleado
     */
    
     int datoSeleccionado = -1;
     
    public VistaEmpleado() {
        initComponents();
        mostrar();
        Mostrar.setVisible(false);
        InsertarEmpleado.setVisible(false);
    }
    
    public void mostrar() {
        try {
            DefaultTableModel modelo;
            CRUDEmpleado emp = new CRUDEmpleado();
            modelo = emp.mostrarDatos();
            TablaEmpleado.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaEmpleado = new javax.swing.JTable();
        BuscarEmpleado = new javax.swing.JTextField();
        EliminarEmpleado = new javax.swing.JButton();
        EditarEmpleado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InsertarEmpleado = new javax.swing.JButton();
        AgregarEmpleado = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión de empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36), new java.awt.Color(0, 102, 255))); // NOI18N

        TablaEmpleado.setBackground(new java.awt.Color(204, 204, 255));
        TablaEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TablaEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        TablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código de empleado", "Nombres", "Apellidos", "Teléfono", "Edad", "Correo", "Dirección"
            }
        ));
        TablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaEmpleado);

        BuscarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        BuscarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BuscarEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        BuscarEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscarEmpleadoFocusLost(evt);
            }
        });
        BuscarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarEmpleadoMouseClicked(evt);
            }
        });
        BuscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarEmpleadoKeyReleased(evt);
            }
        });

        EliminarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EliminarEmpleado.setForeground(new java.awt.Color(51, 102, 255));
        EliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/borrar.png"))); // NOI18N
        EliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEmpleadoActionPerformed(evt);
            }
        });

        EditarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/editar.png"))); // NOI18N
        EditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEmpleadoActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/buscar1.png"))); // NOI18N

        InsertarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        InsertarEmpleado.setForeground(new java.awt.Color(51, 102, 255));
        InsertarEmpleado.setText("Insertar");
        InsertarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarEmpleadoActionPerformed(evt);
            }
        });

        AgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgregarEmpleado.setText("+");
        AgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEmpleadoActionPerformed(evt);
            }
        });

        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(InsertarEmpleado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarEmpleado)
                                .addGap(18, 18, 18)
                                .addComponent(AgregarEmpleado)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addComponent(EditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(EditarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InsertarEmpleado)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpleadoMouseClicked
         datoSeleccionado = TablaEmpleado.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaEmpleadoMouseClicked

    private void EliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEmpleadoActionPerformed
        if (datoSeleccionado >= 0) {
            String Cedula = String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 0));
            CRUDEmpleado emp = new CRUDEmpleado();
            if (JOptionPane.showConfirmDialog(rootPane,
                    "Se eliminará el registro, ¿Desea continuar?",
                    "Eliminar Registro",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                emp.eliminar(Cedula);
                mostrar();
                JOptionPane.showMessageDialog(null,
                        "Dato eliminado correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar un registro de la tabla");
        }
    }//GEN-LAST:event_EliminarEmpleadoActionPerformed

    private void EditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEmpleadoActionPerformed
        Empleado emple = new Empleado();
        int x = (Menu.desktopPane.getWidth() / 2) - emple.getWidth() / 2;
        int y = (Menu.desktopPane.getHeight() / 2) - emple.getHeight() / 2;
        emple.setLocation(x, y);
        Menu.desktopPane.add(emple);

        if (datoSeleccionado >= 0) {
            //mandar datos al formulario
            Empleado.Cedula.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 0)));
            Empleado.NombresE.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 1)));
            Empleado.ApellidosE.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 2)));
            Empleado.DirecEmpleado.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 3)));
            Empleado.TelEmpleado.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 4)));
            Empleado.CorreoE.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 5)));
            Empleado.Edad.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 6)));
            Empleado.Cedula.enable(false);
            //hacer al frente y visible
            emple.toFront();
            Proveedor.GuardarProveedor.setVisible(false);
            Proveedor.ActualizarProveedor.setVisible(true);
            Proveedor.Cancelar.setVisible(true);
            emple.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro a actualizar");
        }
    }//GEN-LAST:event_EditarEmpleadoActionPerformed

    private void BuscarEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarEmpleadoKeyReleased
         try {

            DefaultTableModel modelo;
            CRUDEmpleado emp = new CRUDEmpleado();
            modelo = emp.buscarDatos(BuscarEmpleado.getText());
            TablaEmpleado.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BuscarEmpleadoKeyReleased

    private void AgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEmpleadoActionPerformed
        Empleado emple = new Empleado();
        int x = (Menu.desktopPane.getWidth() / 2) - emple.getWidth() / 2;
        int y = (Menu.desktopPane.getHeight() / 2) - emple.getHeight() / 2;
        emple.setLocation(x, y);
        Menu.desktopPane.add(emple);
        emple.toFront();
        emple.setVisible(true);
    }//GEN-LAST:event_AgregarEmpleadoActionPerformed

    private void BuscarEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarEmpleadoFocusLost
         BuscarEmpleado.setText("Buscar por cédula, nombres o apellidos");
       BuscarEmpleado.setForeground(Color.gray);
    }//GEN-LAST:event_BuscarEmpleadoFocusLost

    private void BuscarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarEmpleadoMouseClicked
         BuscarEmpleado.setText("");
    }//GEN-LAST:event_BuscarEmpleadoMouseClicked

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_MostrarActionPerformed

    private void InsertarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarEmpleadoActionPerformed
         if (datoSeleccionado >=0){
          VistaVenta.CodE.setText(String.valueOf(TablaEmpleado.getValueAt(datoSeleccionado, 0)));
          dispose(); 
          JOptionPane.showMessageDialog(null, "Dato agregado correctamente");
      }else{
         JOptionPane.showMessageDialog(null, "Debe seleccionar un registro"); 
      }
    }//GEN-LAST:event_InsertarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarEmpleado;
    private javax.swing.JTextField BuscarEmpleado;
    public static javax.swing.JButton EditarEmpleado;
    public static javax.swing.JButton EliminarEmpleado;
    public static javax.swing.JButton InsertarEmpleado;
    private javax.swing.JButton Mostrar;
    public static javax.swing.JTable TablaEmpleado;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
