/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.formularios;
import Controlador.CRUDCliente;
import Controlador.CRUDEmpleado;
import Controlador.CRUDProducto;
import Controlador.CRUDVenta;
import Controlador.CRUDVentaProducto;
import Modelo.POJOCliente;
import Modelo.POJOEmpleado;
import Modelo.POJOProducto;
import Modelo.POJOVenta;
import Modelo.POJOVentaProducto;
import Vista.Menu.Menu;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Joy Cruz
 */
public class VistaVenta extends javax.swing.JInternalFrame {

    int DatoSeleccionado = -1;
    /**
     * Creates new form VistaVenta
     */
     DefaultTableModel modelo;
    String[] titulos = {"Código Producto", "Nombre Producto", "Cantidad", "Precio"};
    String[] datos = new String[4];
    int datoSeleccionado;
    int IDProducto;
    
    public VistaVenta() {
        initComponents();
        llenarProductos();
        modelo = new DefaultTableModel(null, titulos);
        Cancelar.setVisible(false);
        ActualizarVenta.setVisible(false);
    }
    
     public void mostrar() {
        try {
//            DefaultTableModel modelo;
//            CRUDVenta venta = new CRUDVenta();
//            modelo = venta.mostrarDatos();
//            TablaVenta.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
    public void llenarProductos() {

        CRUDProducto gr = new CRUDProducto();
        ArrayList<POJOProducto> listaProducto = gr.mostrarDatosCombo();
        ComboProducto.removeAllItems();
        for (int i = 0; i < listaProducto.size(); i++) {
            ComboProducto.addItem(new POJOProducto(
                    listaProducto.get(i).getIDProducto(),
                    listaProducto.get(i).getNomProducto(),
            listaProducto.get(i).getPrecioProducto()));
        }
        limpiar();

    }
     
     public void limpiar() {
        fecha.setText("");
        DirecVenta.setText("");
    }
     
      public void guardarVenta() {

//        CRUDVenta cc = new CRUDVenta();
//
//        POJOVenta cl = new POJOVenta(0,
//                ComboEmpleado.getItemAt(ComboEmpleado.getSelectedIndex()).getIDEmpleado(),
//                ComboCliente.getItemAt(ComboCliente.getSelectedIndex()).getIDCliente(),
//                FechaVenta.getText(),
//                DirecVenta.getText());
//        cc.Guardar(cl);

    }
      
        public void editarVenta() {

//        CRUDVenta cc = new CRUDVenta();
//
//        POJOVenta cl = new POJOVenta(0,
//                ComboEmpleado.getItemAt(ComboEmpleado.getSelectedIndex()).getIDEmpleado(),
//                ComboCliente.getItemAt(ComboCliente.getSelectedIndex()).getIDCliente(),
//                FechaVenta.getText(),
//                DirecVenta.getText());
//        cc.actualizar(cl);

    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JFormattedTextField();
        DirecVenta = new javax.swing.JTextField();
        GuardarVenta = new javax.swing.JButton();
        ActualizarVenta = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CodC = new javax.swing.JTextField();
        AgregarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        CodE = new javax.swing.JTextField();
        AgregarEmpleado = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboProducto = new javax.swing.JComboBox<>();
        AgregarProducto = new javax.swing.JButton();
        EliminarProducto = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Dirección");

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setForeground(new java.awt.Color(51, 51, 51));
        try {
            fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        DirecVenta.setBackground(new java.awt.Color(255, 255, 255));
        DirecVenta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DirecVenta.setForeground(new java.awt.Color(51, 51, 51));

        GuardarVenta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GuardarVenta.setForeground(new java.awt.Color(51, 102, 255));
        GuardarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/disquete.png"))); // NOI18N
        GuardarVenta.setText("Guardar");
        GuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarVentaActionPerformed(evt);
            }
        });

        ActualizarVenta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ActualizarVenta.setForeground(new java.awt.Color(51, 102, 255));
        ActualizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/boton-actualizar.png"))); // NOI18N
        ActualizarVenta.setText("Actualizar");
        ActualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarVentaActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(51, 102, 255));
        Cancelar.setText("Cancelar");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(51, 102, 255))); // NOI18N

        CodC.setBackground(new java.awt.Color(255, 255, 255));

        AgregarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AgregarCliente.setForeground(new java.awt.Color(51, 102, 255));
        AgregarCliente.setText("Agregar");
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodC)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 118, Short.MAX_VALUE)
                        .addComponent(AgregarCliente)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CodC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgregarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(51, 102, 255))); // NOI18N

        CodE.setBackground(new java.awt.Color(255, 255, 255));
        CodE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodEActionPerformed(evt);
            }
        });

        AgregarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AgregarEmpleado.setForeground(new java.awt.Color(51, 102, 255));
        AgregarEmpleado.setText("Agregar");
        AgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AgregarEmpleado)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CodE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AgregarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(51, 102, 255))); // NOI18N

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código de Producto", "Nombre de Producto", "Cantidad ", "Precio"
            }
        ));
        TablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProducto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Productos");

        Cantidad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Cantidad de productos vendidos");

        AgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgregarProducto.setText("+");
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });

        EliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/borrar.png"))); // NOI18N
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ActualizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GuardarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirecVenta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(ComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(Cantidad))
                                .addGap(18, 18, 18)
                                .addComponent(AgregarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EliminarProducto)))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarProducto)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AgregarProducto)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DirecVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ActualizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GuardarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarVentaActionPerformed
       try {
            if ((fecha.getText().equals(""))
                    || (CodC.getText().equals("   -      -     "))
                    || (CodE.getText().equals("   -      -     "))
                    || (DirecVenta.getText().equals(""))) {
                JOptionPane.showMessageDialog(null,
                        "Tiene datos vacíos");
            } else if(TablaProducto.getRowCount()<0){
                JOptionPane.showMessageDialog(null, "Debe añadir a la tabla al menos un producto");
            }
            else {
                String FechaVenta = (fecha.getText().toString());
                String CedulaE = (CodE.getText().toString());
                String CedulaC = (CodC.getText().toString());
                String Direccion = (DirecVenta.getText().toString());
                
                POJOVenta cc = new POJOVenta(CedulaE, CedulaC, FechaVenta, Direccion);
                CRUDVenta com = new CRUDVenta();
                com.Guardar(cc);
                
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    int IDProducto = Integer.parseInt(TablaProducto.getValueAt(i, 0).toString());
                    int CantProductosVendidos = Integer.parseInt(TablaProducto.getValueAt(i, 2).toString());
                    POJOVentaProducto cg = new POJOVentaProducto(IDProducto, CantProductosVendidos);
                    CRUDVentaProducto ccg = new CRUDVentaProducto();
                    ccg.InsertarVentaProducto(cg);
                }
                JOptionPane.showMessageDialog(null, "Datos Guardados correctamente");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro" + e);

        }
    }//GEN-LAST:event_GuardarVentaActionPerformed

    private void ActualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarVentaActionPerformed
//         try {
//            if ((CodigoVenta.getText().equals(""))
//                    ||(ComboEmpleado.getItemAt(ComboEmpleado.getSelectedIndex()).equals(""))
//                    ||(ComboCliente.getItemAt(ComboCliente.getSelectedIndex()).equals(""))
//                    || (FechaVenta.getText().equals(""))
//                    || (DirecVenta.getText().equals(""))) {
//                JOptionPane.showMessageDialog(null, "Tiene datos vacíos");
//            } else {
//                editarVenta();
//                mostrar();
//                limpiar();
//                ActualizarVenta.setVisible(false);
//                Cancelar.setVisible(false);
//                JOptionPane.showMessageDialog(null, "Datos Actualizados Correctamente");
//                
//
//            }
//
//        } catch (HeadlessException e) {
//            JOptionPane.showMessageDialog(null, "Error: " + e);
//        }
    }//GEN-LAST:event_ActualizarVentaActionPerformed

    private void AgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEmpleadoActionPerformed
        VistaEmpleado emple = new VistaEmpleado();
        int x = (Menu.desktopPane.getWidth() / 2) - emple.getWidth() / 2;
        int y = (Menu.desktopPane.getHeight() / 2) - emple.getHeight() / 2;
        emple.setLocation(x, y);
        Menu.desktopPane.add(emple);
        emple.toFront();
        emple.setVisible(true);
        VistaEmpleado.InsertarEmpleado.setVisible(true);
        VistaEmpleado.EditarEmpleado.setVisible(false);
        VistaEmpleado.EliminarEmpleado.setVisible(false);
    }//GEN-LAST:event_AgregarEmpleadoActionPerformed

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        VistaCliente cli = new VistaCliente();
        int x = (Menu.desktopPane.getWidth() / 2) - cli.getWidth() / 2;
        int y = (Menu.desktopPane.getHeight() / 2) - cli.getHeight() / 2;
        cli.setLocation(x, y);
        Menu.desktopPane.add(cli);
        cli.toFront();
        cli.setVisible(true);
        VistaCliente.InsertarCliente.setVisible(true);
        VistaCliente.EditarCliente.setVisible(false);
        VistaCliente.EliminarCliente.setVisible(false);
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void CodEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodEActionPerformed

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
         try {
            CRUDProducto gr = new CRUDProducto();
            boolean band = true;
            int cod = ComboProducto.getItemAt(ComboProducto.getSelectedIndex()).getIDProducto();
            String nombre = ComboProducto.getItemAt(ComboProducto.getSelectedIndex()).getNomProducto();
            Double precio = ComboProducto.getItemAt(ComboProducto.getSelectedIndex()).getPrecioProducto();
            String cant = Cantidad.getText();
            if (modelo.getRowCount() >= 0) {
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    int dato = Integer.parseInt(TablaProducto.getValueAt(i, 0).toString());
                    if (cod != dato) {
                    } else {
                        band = false;
                    }
                }
            }
            if (band) {
                datos[0] = String.valueOf(cod);
                datos[1] = nombre;
                datos[2] = cant;
                datos[3] = String.valueOf(precio);
                modelo.addRow(datos);
                TablaProducto.setModel(modelo);
            } else {
                JOptionPane.showMessageDialog(null, "Dato ya ha sido agregado");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void TablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductoMouseClicked
        DatoSeleccionado = TablaProducto.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaProductoMouseClicked

    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        if (datoSeleccionado >= 0) {
            int fila = TablaProducto.getSelectedRow();
            modelo.removeRow(fila);
        } else
            JOptionPane.showConfirmDialog(null, "Seleccione el dato a eliminar");
    }//GEN-LAST:event_EliminarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarVenta;
    private javax.swing.JButton AgregarCliente;
    private javax.swing.JButton AgregarEmpleado;
    private javax.swing.JButton AgregarProducto;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Cantidad;
    public static javax.swing.JTextField CodC;
    public static javax.swing.JTextField CodE;
    private javax.swing.JComboBox<POJOProducto> ComboProducto;
    private javax.swing.JTextField DirecVenta;
    private javax.swing.JButton EliminarProducto;
    private javax.swing.JButton GuardarVenta;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
